FROM golang:alpine as builder
LABEL authors="emresin"

RUN apk update && apk add --no-cache git bash build-base

RUN mkdir src/app
WORKDIR src/app
COPY . .
RUN go mod tidy
RUN go build -o /app/job ./cmd/job

FROM  alpine

COPY --from=builder /app/job /app/job

CMD /app/job
