version: '3.8'
services:
  job:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.job
    depends_on:
      db:
        condition: service_healthy
      service:
        condition: service_started


  service:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.service
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  pgdata: